export {addRevue} from "./addRevues.js"
export {deleteRevue} from "./removeRevues.js"
export {getRevues} from "./getRevues.js"
export {getRevueById} from "./getRevuesByid.js"
export {incrementVue , incrementTelechargement} from "./incrementVueRevues.js"